import React from "react";

const iconss=[
    {
        name:":v",
        code:"U+1F600",
        Value:"😀"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":))",
        code:"U+1F602",
        Value:"😂"
    },
    {
        name:"rolling on the floor laughing",
        code:"U+1F923",
        Value:"🤣"
    },
    {
        name:"smiling face with open mouth",
        code:"U+1F603",
        Value:"😃"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    {
        name:":d",
        code:"U+1F601",
        Value:"😁"
    },
    
    ]
export default class Icon extends React.PureComponent{
        render(){
        
        return(
            <>
            {
                iconss.map((item,index)=>{
                   
               return(  
                <React.Fragment key={index}>
                        <li data-name={item.name} onClick={(i)=>this.props.onClick(item.Value,this.props.id)}>
               <a className="fg-emoji-picker-item" title={item.name} data-name={item.name} data-code={iconss.code} href="##">
              {item.Value}</a>
               </li>
                </React.Fragment>   );
                })
            }
            </>
        );
  
    }
    
}